Repository Polaroid-Soen-341/SOEN341, pull requests merged in 2021-02, with the labels that each got.

#2 #1 Readme initial update
  README.md
Labels: documentation

#12 Develop
  README.md
Labels: documentation

#15 #14 Integrate Vue.js for frontend
  README.md
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/assets/logo.svg
  frontend/src/components/HelloWorld.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/store/index.js
  frontend/src/views/About.vue
  frontend/src/views/Home.vue
  frontend/vue.config.js
Labels: Front end, documentation, enhancement

#24 Travis implementation
  .travis.yml
Labels: Back end

#35 removing local directory for from travis.yml
  .travis.yml
Labels: Back end, bug
